stages:
- test
- publish
- deploy

test-code:
  stage: test
  only:
    - develop
  image: docker
  services:
    - docker:dind
  script:
  - apk add curl make nodejs npm sudo bash
  - curl -s https://raw.githubusercontent.com/ask-ell/ask/refs/heads/release/install.sh | bash
  - ask test
  - ask build

test-publish:
  stage: test
  only:
    - develop
  image: docker
  services:
    - docker:dind
  script:
  - apk add curl make nodejs npm sudo bash
  - curl -s https://raw.githubusercontent.com/ask-ell/ask/refs/heads/release/install.sh | bash
  - ask build
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  - docker buildx create --driver docker-container --use
  - BUILDX="docker buildx build --platform linux/amd64,linux/arm64"
  - $BUILDX -t "$CI_REGISTRY_IMAGE/back-end:$CI_COMMIT_BRANCH" --file .ask/config/back-end/Dockerfile --push .
  environment: pre-production

publish:
  stage: publish
  only:
    - release
  image: docker
  services:
    - docker:dind
  script:
  - apk add curl make nodejs npm sudo bash
  - curl -s https://raw.githubusercontent.com/ask-ell/ask/refs/heads/release/install.sh | bash
  - ask build
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  - docker buildx create --driver docker-container --use
  - BUILDX="docker buildx build --platform linux/amd64,linux/arm64"
  - $BUILDX -t "$CI_REGISTRY_IMAGE/back-end:$CI_COMMIT_BRANCH" --file .ask/config/back-end/Dockerfile --push .
  environment: production
