networks:
  default:
    driver: "bridge"

secrets:
  ask:
    file: secrets.json

volumes:
  source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD

services:
  root:
    image: node:20.19.2
    networks:
    - default
    user: node
    working_dir: /home/node/workspace
    environment:
      NX_DAEMON: true
    volumes:
    - source:/home/node/workspace
    ports:
    - "3000:3000"
    secrets:
    - ask
    command: npm run start:dev -- --host=0.0.0.0
