networks:
  default:
    driver: 'overlay'

  public-proxy:
    external: true

secrets:
  ask:
    file: secrets.json

services:
  back-end:
    image: ask/back-end:develop
    networks:
      - default
    secrets:
      - ask
