networks:
  default:
    driver: "overlay"

  public-proxy:
    external: true

secrets:
  ask:
    file: secrets.json

services:
  back-end:
    image: ask-ell/ask-back-end:develop
    networks:
    - default
    secrets:
    - ask