export const UNIT_OF_WORK_PROVIDER = Symbol('UNIT_OF_WORK_PROVIDER');
export const FIND_ONE_PROJECT_CONFIGURATION_USE_CASE = Symbol('FIND_ONE_PROJECT_CONFIGURATION_USE_CASE');
export const SAVE_PROJECT_CONFIGURATION_USE_CASE = Symbol('SAVE_PROJECT_CONFIGURATION_USE_CASE');
